In [2]:
import pandas as pd

In [3]:
pd.__version__

'3.0.6'

In [41]:
urbannest_df = pd.read_csv("data/UrbanNest_Retail_Dirty_Customer_Order_Dataset.csv")
urbannest_df["order_date"] = pd.to_datetime(
    urbannest_df["order_date"], format="%Y-%m-%d", errors="coerce"
)

In [18]:
urbannest_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       5000 non-null   str
 1   order_id          5000 non-null   str
 2   product_id        5000 non-null   str
 3   phone_number      5000 non-null   int64
 4   customer_name     5000 non-null   str
 5   gender            4020 non-null   str
 6   age_group         4137 non-null   str
 7   city              5000 non-null   str
 8   region            5000 non-null   str
 9   customer_segment  4615 non-null   str
 10  order_date        5000 non-null   datetime64[us]
 11  product_category  5000 non-null   str
 12  product_name      5000 non-null   str
 13  quantity          5000 non-null   int64
 14  unit_price        5000 non-null   int64
 15  discount_rate     5000 non-null   float64
 16  order_revenue     5000 non-null   float64
 17  delivery_fee      5000 non-null   int64
 18  payment_method    4585 non-null   str
 19  sales_channel     4589 non-null   str
 20  order_status      4295 non-null   str
 21  delivery_status   4206 non-null   str
 22  delivery_days     4582 non-null   float64
 23  customer_rating   4495 non-null   float64
 24  return_flag       4015 non-null   str
dtypes: datetime64[us](1), float64(4), int64(4), str(16)
memory usage: 976.7 KB

In [8]:
urbannest_df.head(5)

,customer_id,order_id,product_id,phone_number,customer_name,gender,age_group,city,region,customer_segment,...,discount_rate,order_revenue,delivery_fee,payment_method,sales_channel,order_status,delivery_status,delivery_days,customer_rating,return_flag
0,CUST00001,ORD000001,PRD0017,2348082692761,Customer 1,NaN,60+,Abuja,North Central,Occasional,...,0.20,40000.0,2500,Bank Transfer,Mobile App,cancelled,delivered,2.0,4.0,NO
1,CUST00002,ORD000002,PRD0004,2348059532120,Customer 2,Male,46-60,Kaduna,North West,NaN,...,0.05,76000.0,1000,Card,Instagram,Completed,Delayed,14.0,5.0,No
2,CUST00003,ORD000003,PRD0002,2348056395726,Customer 3,F,60+,Kaduna,North West,Regular,...,0.00,375000.0,0,Card,Mobile App,NaN,delivered,1.0,NaN,Yes
3,CUST00004,ORD000004,PRD0020,2348080821128,Customer 4,Female,46-60,Port Harcourt,South South,Regular,...,0.00,375000.0,1000,Cash on Delivery,Store,Returned,Delayed,5.0,4.0,No
4,CUST00005,ORD000005,PRD0021,2348036427770,Customer 5,MALE,60+,Port Harcourt,South South,Premium,...,0.20,14000.0,2500,Wallet,Store,Completed,delivered,10.0,3.0,No

In [11]:
urbannest_df.tail

<bound method NDFrame.tail of      customer_id   order_id product_id   phone_number    customer_name  \
0      CUST00001  ORD000001    PRD0017  2348082692761       Customer 1
1      CUST00002  ORD000002    PRD0004  2348059532120       Customer 2
2      CUST00003  ORD000003    PRD0002  2348056395726       Customer 3
3      CUST00004  ORD000004    PRD0020  2348080821128       Customer 4
4      CUST00005  ORD000005    PRD0021  2348036427770       Customer 5
...          ...        ...        ...            ...              ...
4995   CUST04996  ORD004996    PRD0008  2348082415426    Customer 4996
4996   CUST04997  ORD004997    PRD0030  2348094150958    Customer 4997
4997   CUST04998  ORD004998    PRD0002  2348052007276    Customer 4998
4998   CUST04999  ORD004999    PRD0021  2348078351557    Customer 4999
4999   CUST05000  ORD005000    PRD0010  2348075328308   Customer 5000

      gender age_group           city         region customer_segment  ...  \
0        NaN       60+          Abuja  North Central       Occasional  ...
1       Male     46-60         Kaduna     North West              NaN  ...
2          F       60+         Kaduna     North West          Regular  ...
3     Female     46-60  Port Harcourt    South South          Regular  ...
4       MALE       60+  Port Harcourt    South South          Premium  ...
...      ...       ...            ...            ...              ...  ...
4995     NaN       NaN           Kano     North West         premium   ...
4996    Male       60+         Kaduna     North West          Regular  ...
4997     NaN     36-45          Abuja  North Central         premium   ...
4998    Male     18-25     Benin City    South South         premium   ...
4999     NaN     36-45         Ibadan     South West          Regular  ...

     discount_rate order_revenue delivery_fee    payment_method  \
0             0.20       40000.0         2500     Bank Transfer
1             0.05       76000.0         1000              Card
2             0.00      375000.0            0              Card
3             0.00      375000.0         1000  Cash on Delivery
4             0.20       14000.0         2500            Wallet
...            ...           ...          ...               ...
4995          0.05      570000.0         2500     Bank Transfer
4996          0.05       42750.0            0     Bank Transfer
4997          0.15       17000.0         3500              USSD
4998          0.10      216000.0         1000  Cash on Delivery
4999          0.05       35625.0         3500     bank transfer

      sales_channel  order_status  delivery_status  delivery_days  \
0        Mobile App     cancelled        delivered            2.0
1         Instagram     Completed          Delayed           14.0
2        Mobile App           NaN        delivered            1.0
3             Store      Returned          Delayed            5.0
4             Store     Completed        delivered           10.0
...             ...           ...              ...            ...
4995      Instagram     completed        Delivered            NaN
4996    Marketplace      Returned       In Transit            NaN
4997     mobile app     Completed       In Transit            4.0
4998        website     completed        Delivered           13.0
4999          Store     Completed       In Transit           11.0

     customer_rating return_flag
0                4.0          NO
1                5.0          No
2                NaN         Yes
3                4.0          No
4                3.0          No
...              ...         ...
4995             4.0          No
4996             4.0          No
4997             4.0         yes
4998             4.0         Yes
4999             4.0          NO

[5000 rows x 25 columns]>

In [9]:
urbannest_df.columns

Index(['customer_id', 'order_id', 'product_id', 'phone_number',
       'customer_name', 'gender', 'age_group', 'city', 'region',
       'customer_segment', 'order_date', 'product_category', 'product_name',
       'quantity', 'unit_price', 'discount_rate', 'order_revenue',
       'delivery_fee', 'payment_method', 'sales_channel', 'order_status',
       'delivery_status', 'delivery_days', 'customer_rating', 'return_flag'],
      dtype='str')

In [10]:
urbannest_df.info

<bound method DataFrame.info of      customer_id   order_id product_id   phone_number    customer_name  \
0      CUST00001  ORD000001    PRD0017  2348082692761       Customer 1
1      CUST00002  ORD000002    PRD0004  2348059532120       Customer 2
2      CUST00003  ORD000003    PRD0002  2348056395726       Customer 3
3      CUST00004  ORD000004    PRD0020  2348080821128       Customer 4
4      CUST00005  ORD000005    PRD0021  2348036427770       Customer 5
...          ...        ...        ...            ...              ...
4995   CUST04996  ORD004996    PRD0008  2348082415426    Customer 4996
4996   CUST04997  ORD004997    PRD0030  2348094150958    Customer 4997
4997   CUST04998  ORD004998    PRD0002  2348052007276    Customer 4998
4998   CUST04999  ORD004999    PRD0021  2348078351557    Customer 4999
4999   CUST05000  ORD005000    PRD0010  2348075328308   Customer 5000

      gender age_group           city         region customer_segment  ...  \
0        NaN       60+          Abuja  North Central       Occasional  ...
1       Male     46-60         Kaduna     North West              NaN  ...
2          F       60+         Kaduna     North West          Regular  ...
3     Female     46-60  Port Harcourt    South South          Regular  ...
4       MALE       60+  Port Harcourt    South South          Premium  ...
...      ...       ...            ...            ...              ...  ...
4995     NaN       NaN           Kano     North West         premium   ...
4996    Male       60+         Kaduna     North West          Regular  ...
4997     NaN     36-45          Abuja  North Central         premium   ...
4998    Male     18-25     Benin City    South South         premium   ...
4999     NaN     36-45         Ibadan     South West          Regular  ...

     discount_rate order_revenue delivery_fee    payment_method  \
0             0.20       40000.0         2500     Bank Transfer
1             0.05       76000.0         1000              Card
2             0.00      375000.0            0              Card
3             0.00      375000.0         1000  Cash on Delivery
4             0.20       14000.0         2500            Wallet
...            ...           ...          ...               ...
4995          0.05      570000.0         2500     Bank Transfer
4996          0.05       42750.0            0     Bank Transfer
4997          0.15       17000.0         3500              USSD
4998          0.10      216000.0         1000  Cash on Delivery
4999          0.05       35625.0         3500     bank transfer

      sales_channel  order_status  delivery_status  delivery_days  \
0        Mobile App     cancelled        delivered            2.0
1         Instagram     Completed          Delayed           14.0
2        Mobile App           NaN        delivered            1.0
3             Store      Returned          Delayed            5.0
4             Store     Completed        delivered           10.0
...             ...           ...              ...            ...
4995      Instagram     completed        Delivered            NaN
4996    Marketplace      Returned       In Transit            NaN
4997     mobile app     Completed       In Transit            4.0
4998        website     completed        Delivered           13.0
4999          Store     Completed       In Transit           11.0

     customer_rating return_flag
0                4.0          NO
1                5.0          No
2                NaN         Yes
3                4.0          No
4                3.0          No
...              ...         ...
4995             4.0          No
4996             4.0          No
4997             4.0         yes
4998             4.0         Yes
4999             4.0          NO

[5000 rows x 25 columns]>

In [12]:
urbannest_df.info

<bound method DataFrame.info of      customer_id   order_id product_id   phone_number    customer_name  \
0      CUST00001  ORD000001    PRD0017  2348082692761       Customer 1
1      CUST00002  ORD000002    PRD0004  2348059532120       Customer 2
2      CUST00003  ORD000003    PRD0002  2348056395726       Customer 3
3      CUST00004  ORD000004    PRD0020  2348080821128       Customer 4
4      CUST00005  ORD000005    PRD0021  2348036427770       Customer 5
...          ...        ...        ...            ...              ...
4995   CUST04996  ORD004996    PRD0008  2348082415426    Customer 4996
4996   CUST04997  ORD004997    PRD0030  2348094150958    Customer 4997
4997   CUST04998  ORD004998    PRD0002  2348052007276    Customer 4998
4998   CUST04999  ORD004999    PRD0021  2348078351557    Customer 4999
4999   CUST05000  ORD005000    PRD0010  2348075328308   Customer 5000

      gender age_group           city         region customer_segment  ...  \
0        NaN       60+          Abuja  North Central       Occasional  ...
1       Male     46-60         Kaduna     North West              NaN  ...
2          F       60+         Kaduna     North West          Regular  ...
3     Female     46-60  Port Harcourt    South South          Regular  ...
4       MALE       60+  Port Harcourt    South South          Premium  ...
...      ...       ...            ...            ...              ...  ...
4995     NaN       NaN           Kano     North West         premium   ...
4996    Male       60+         Kaduna     North West          Regular  ...
4997     NaN     36-45          Abuja  North Central         premium   ...
4998    Male     18-25     Benin City    South South         premium   ...
4999     NaN     36-45         Ibadan     South West          Regular  ...

     discount_rate order_revenue delivery_fee    payment_method  \
0             0.20       40000.0         2500     Bank Transfer
1             0.05       76000.0         1000              Card
2             0.00      375000.0            0              Card
3             0.00      375000.0         1000  Cash on Delivery
4             0.20       14000.0         2500            Wallet
...            ...           ...          ...               ...
4995          0.05      570000.0         2500     Bank Transfer
4996          0.05       42750.0            0     Bank Transfer
4997          0.15       17000.0         3500              USSD
4998          0.10      216000.0         1000  Cash on Delivery
4999          0.05       35625.0         3500     bank transfer

      sales_channel  order_status  delivery_status  delivery_days  \
0        Mobile App     cancelled        delivered            2.0
1         Instagram     Completed          Delayed           14.0
2        Mobile App           NaN        delivered            1.0
3             Store      Returned          Delayed            5.0
4             Store     Completed        delivered           10.0
...             ...           ...              ...            ...
4995      Instagram     completed        Delivered            NaN
4996    Marketplace      Returned       In Transit            NaN
4997     mobile app     Completed       In Transit            4.0
4998        website     completed        Delivered           13.0
4999          Store     Completed       In Transit           11.0

     customer_rating return_flag
0                4.0          NO
1                5.0          No
2                NaN         Yes
3                4.0          No
4                3.0          No
...              ...         ...
4995             4.0          No
4996             4.0          No
4997             4.0         yes
4998             4.0         Yes
4999             4.0          NO

[5000 rows x 25 columns]>

In [13]:
urbannest_df.sample(5)

,customer_id,order_id,product_id,phone_number,customer_name,gender,age_group,city,region,customer_segment,...,discount_rate,order_revenue,delivery_fee,payment_method,sales_channel,order_status,delivery_status,delivery_days,customer_rating,return_flag
74,CUST00075,ORD000075,PRD0009,2348019314288,Customer 75,M,36-45,Port Harcourt,South South,Regular,...,0.15,102000.0,1000,Cash on Delivery,NaN,pending,delivered,4.0,1.0,Yes
2157,CUST02158,ORD002158,PRD0027,2348062664431,Customer 2158,Male,36-45,Ibadan,South West,Business,...,0.00,60000.0,0,bank transfer,Marketplace,Completed,NaN,14.0,3.0,Yes
674,CUST00675,ORD000675,PRD0023,2348017643688,Customer 675,NaN,26-35,Ibadan,South West,Premium,...,0.00,75000.0,0,USSD,Instagram,NaN,Delivered,13.0,5.0,Yes
2139,CUST02140,ORD002140,PRD0013,2348082928111,Customer 2140,NaN,46-60,Kaduna,North West,Occasional,...,0.20,300000.0,1000,Cash on Delivery,Marketplace,pending,delivered,5.0,NaN,NaN
3577,CUST03578,ORD003578,PRD0014,2348076781192,Customer 3578,Female,36-45,Kano,North West,Occasional,...,0.15,11900.0,3500,Wallet,Store,Completed,In Transit,6.0,4.0,No

In [15]:
urbannest_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       5000 non-null   str
 1   order_id          5000 non-null   str
 2   product_id        5000 non-null   str
 3   phone_number      5000 non-null   int64
 4   customer_name     5000 non-null   str
 5   gender            4020 non-null   str
 6   age_group         4137 non-null   str
 7   city              5000 non-null   str
 8   region            5000 non-null   str
 9   customer_segment  4615 non-null   str
 10  order_date        5000 non-null   datetime64[us]
 11  product_category  5000 non-null   str
 12  product_name      5000 non-null   str
 13  quantity          5000 non-null   int64
 14  unit_price        5000 non-null   int64
 15  discount_rate     5000 non-null   float64
 16  order_revenue     5000 non-null   float64
 17  delivery_fee      5000 non-null   int64
 18  payment_method    4585 non-null   str
 19  sales_channel     4589 non-null   str
 20  order_status      4295 non-null   str
 21  delivery_status   4206 non-null   str
 22  delivery_days     4582 non-null   float64
 23  customer_rating   4495 non-null   float64
 24  return_flag       4015 non-null   str
dtypes: datetime64[us](1), float64(4), int64(4), str(16)
memory usage: 976.7 KB

In [15]:
urbannest_df.shape

(5000, 25)

In [ ]:
urbannest_df.columns

Index(['customer_id', 'order_id', 'product_id', 'phone_number',
       'customer_name', 'gender', 'age_group', 'city', 'region',
       'customer_segment', 'order_date', 'product_category', 'product_name',
       'quantity', 'unit_price', 'discount_rate', 'order_revenue',
       'delivery_fee', 'payment_method', 'sales_channel', 'order_status',
       'delivery_status', 'delivery_days', 'customer_rating', 'return_flag'],
      dtype='str')

In [5]:
df = pd.DataFrame({
    'date_column': ['2021-01-01', '2021-02-01', '2021-03-01', '2021-04-01', '2021-05-01']
})

In [6]:
print("Original:")
print(df)

Original:
  date_column
0  2021-01-01
1  2021-02-01
2  2021-03-01
3  2021-04-01
4  2021-05-01

In [31]:
# Convert the 'date_column' to datetime format
df['date_column'] = pd.to_datetime(df['date_column'], format='%Y-%m-%d')
print("\nfixed:")
print(df)
print(df.dtypes)

fixed:
  date_column
0  2021-01-01
1  2021-02-01
2  2021-03-01
3  2021-04-01
4  2021-05-01
date_column    datetime64[us]
dtype: object

In [13]:
urbannest_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       5000 non-null   str
 1   order_id          5000 non-null   str
 2   product_id        5000 non-null   str
 3   phone_number      5000 non-null   int64
 4   customer_name     5000 non-null   str
 5   gender            4020 non-null   str
 6   age_group         4137 non-null   str
 7   city              5000 non-null   str
 8   region            5000 non-null   str
 9   customer_segment  4615 non-null   str
 10  order_date        5000 non-null   str
 11  product_category  5000 non-null   str
 12  product_name      5000 non-null   str
 13  quantity          5000 non-null   int64
 14  unit_price        5000 non-null   int64
 15  discount_rate     5000 non-null   float64
 16  order_revenue     5000 non-null   float64
 17  delivery_fee      5000 non-null   int64
 18  payment_method    4585 non-null   str
 19  sales_channel     4589 non-null   str
 20  order_status      4295 non-null   str
 21  delivery_status   4206 non-null   str
 22  delivery_days     4582 non-null   float64
 23  customer_rating   4495 non-null   float64
 24  return_flag       4015 non-null   str
dtypes: float64(4), int64(4), str(17)
memory usage: 976.7 KB

In [23]:
print(df['date_column'].dtype)

datetime64[us]

In [29]:
print(urbannest_df['gender'].head())

0       NaN
1      Male
2         F
3    Female
4      MALE
Name: gender, dtype: str

In [32]:
print(urbannest_df['order_date'].head())

0    2024-01-29
1    2024-10-23
2    2026-06-22
3    2025-12-08
4    2026-06-14
Name: order_date, dtype: str

In [36]:
urbannest_df.head(5)

,customer_id,order_id,product_id,phone_number,customer_name,gender,age_group,city,region,customer_segment,...,discount_rate,order_revenue,delivery_fee,payment_method,sales_channel,order_status,delivery_status,delivery_days,customer_rating,return_flag
0,CUST00001,ORD000001,PRD0017,2348082692761,Customer 1,NaN,60+,Abuja,North Central,Occasional,...,0.20,40000.0,2500,Bank Transfer,Mobile App,cancelled,delivered,2.0,4.0,NO
1,CUST00002,ORD000002,PRD0004,2348059532120,Customer 2,Male,46-60,Kaduna,North West,NaN,...,0.05,76000.0,1000,Card,Instagram,Completed,Delayed,14.0,5.0,No
2,CUST00003,ORD000003,PRD0002,2348056395726,Customer 3,F,60+,Kaduna,North West,Regular,...,0.00,375000.0,0,Card,Mobile App,NaN,delivered,1.0,NaN,Yes
3,CUST00004,ORD000004,PRD0020,2348080821128,Customer 4,Female,46-60,Port Harcourt,South South,Regular,...,0.00,375000.0,1000,Cash on Delivery,Store,Returned,Delayed,5.0,4.0,No
4,CUST00005,ORD000005,PRD0021,2348036427770,Customer 5,MALE,60+,Port Harcourt,South South,Premium,...,0.20,14000.0,2500,Wallet,Store,Completed,delivered,10.0,3.0,No

In [43]:
urbannest_df.head(5)

,customer_id,order_id,product_id,phone_number,customer_name,gender,age_group,city,region,customer_segment,...,discount_rate,order_revenue,delivery_fee,payment_method,sales_channel,order_status,delivery_status,delivery_days,customer_rating,return_flag
0,CUST00001,ORD000001,PRD0017,2348082692761,Customer 1,NaN,60+,Abuja,North Central,Occasional,...,0.20,40000.0,2500,Bank Transfer,Mobile App,cancelled,delivered,2.0,4.0,NO
1,CUST00002,ORD000002,PRD0004,2348059532120,Customer 2,Male,46-60,Kaduna,North West,NaN,...,0.05,76000.0,1000,Card,Instagram,Completed,Delayed,14.0,5.0,No
2,CUST00003,ORD000003,PRD0002,2348056395726,Customer 3,F,60+,Kaduna,North West,Regular,...,0.00,375000.0,0,Card,Mobile App,NaN,delivered,1.0,NaN,Yes
3,CUST00004,ORD000004,PRD0020,2348080821128,Customer 4,Female,46-60,Port Harcourt,South South,Regular,...,0.00,375000.0,1000,Cash on Delivery,Store,Returned,Delayed,5.0,4.0,No
4,CUST00005,ORD000005,PRD0021,2348036427770,Customer 5,MALE,60+,Port Harcourt,South South,Premium,...,0.20,14000.0,2500,Wallet,Store,Completed,delivered,10.0,3.0,No

In [45]:
db_username = 'postgres'
password = 'password'
host = 'localhost'
port = '5432'
database = 'urbannest_db'

from sqlalchemy import create_engine

engine = create_engine(f'postgresql+psycopg2://{db_username}:{password}@{host}:{port}/{database}')

table_name = 'urbannest_data'

urbannest_df.to_sql(name=table_name, con=engine, if_exists='replace', index=False)

1000