In [35]:
import pandas as pd

In [36]:
pd.__version__

'3.0.6'

In [37]:
urbannest_df = pd.read_csv("data/UrbanNest_Retail_Dirty_Customer_Order_Dataset.csv")

In [38]:
urbannest_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       5000 non-null   str
 1   order_id          5000 non-null   str
 2   product_id        5000 non-null   str
 3   phone_number      5000 non-null   int64
 4   customer_name     5000 non-null   str
 5   gender            4020 non-null   str
 6   age_group         4137 non-null   str
 7   city              5000 non-null   str
 8   region            5000 non-null   str
 9   customer_segment  4615 non-null   str
 10  order_date        5000 non-null   str
 11  product_category  5000 non-null   str
 12  product_name      5000 non-null   str
 13  quantity          5000 non-null   int64
 14  unit_price        5000 non-null   int64
 15  discount_rate     5000 non-null   float64
 16  order_revenue     5000 non-null   float64
 17  delivery_fee      5000 non-null   int64
 18  payment_method    4585 non-null   str
 19  sales_channel     4589 non-null   str
 20  order_status      4295 non-null   str
 21  delivery_status   4206 non-null   str
 22  delivery_days     4582 non-null   float64
 23  customer_rating   4495 non-null   float64
 24  return_flag       4015 non-null   str
dtypes: float64(4), int64(4), str(17)
memory usage: 976.7 KB

In [39]:
urbannest_df.head(5)

,customer_id,order_id,product_id,phone_number,customer_name,gender,age_group,city,region,customer_segment,...,discount_rate,order_revenue,delivery_fee,payment_method,sales_channel,order_status,delivery_status,delivery_days,customer_rating,return_flag
0,CUST00001,ORD000001,PRD0017,2348082692761,Customer 1,NaN,60+,Abuja,North Central,Occasional,...,0.20,40000.0,2500,Bank Transfer,Mobile App,cancelled,delivered,2.0,4.0,NO
1,CUST00002,ORD000002,PRD0004,2348059532120,Customer 2,Male,46-60,Kaduna,North West,NaN,...,0.05,76000.0,1000,Card,Instagram,Completed,Delayed,14.0,5.0,No
2,CUST00003,ORD000003,PRD0002,2348056395726,Customer 3,F,60+,Kaduna,North West,Regular,...,0.00,375000.0,0,Card,Mobile App,NaN,delivered,1.0,NaN,Yes
3,CUST00004,ORD000004,PRD0020,2348080821128,Customer 4,Female,46-60,Port Harcourt,South South,Regular,...,0.00,375000.0,1000,Cash on Delivery,Store,Returned,Delayed,5.0,4.0,No
4,CUST00005,ORD000005,PRD0021,2348036427770,Customer 5,MALE,60+,Port Harcourt,South South,Premium,...,0.20,14000.0,2500,Wallet,Store,Completed,delivered,10.0,3.0,No

In [40]:
urbannest_df.tail()

,customer_id,order_id,product_id,phone_number,customer_name,gender,age_group,city,region,customer_segment,...,discount_rate,order_revenue,delivery_fee,payment_method,sales_channel,order_status,delivery_status,delivery_days,customer_rating,return_flag
4995,CUST04996,ORD004996,PRD0008,2348082415426,Customer 4996,NaN,NaN,Kano,North West,premium,...,0.05,570000.0,2500,Bank Transfer,Instagram,completed,Delivered,NaN,4.0,No
4996,CUST04997,ORD004997,PRD0030,2348094150958,Customer 4997,Male,60+,Kaduna,North West,Regular,...,0.05,42750.0,0,Bank Transfer,Marketplace,Returned,In Transit,NaN,4.0,No
4997,CUST04998,ORD004998,PRD0002,2348052007276,Customer 4998,NaN,36-45,Abuja,North Central,premium,...,0.15,17000.0,3500,USSD,mobile app,Completed,In Transit,4.0,4.0,yes
4998,CUST04999,ORD004999,PRD0021,2348078351557,Customer 4999,Male,18-25,Benin City,South South,premium,...,0.10,216000.0,1000,Cash on Delivery,website,completed,Delivered,13.0,4.0,Yes
4999,CUST05000,ORD005000,PRD0010,2348075328308,Customer 5000,NaN,36-45,Ibadan,South West,Regular,...,0.05,35625.0,3500,bank transfer,Store,Completed,In Transit,11.0,4.0,NO

In [41]:
list(urbannest_df.columns)

['customer_id',
 'order_id',
 'product_id',
 'phone_number',
 'customer_name',
 'gender',
 'age_group',
 'city',
 'region',
 'customer_segment',
 'order_date',
 'product_category',
 'product_name',
 'quantity',
 'unit_price',
 'discount_rate',
 'order_revenue',
 'delivery_fee',
 'payment_method',
 'sales_channel',
 'order_status',
 'delivery_status',
 'delivery_days',
 'customer_rating',
 'return_flag']

In [42]:
urbannest_df.sample(5)

,customer_id,order_id,product_id,phone_number,customer_name,gender,age_group,city,region,customer_segment,...,discount_rate,order_revenue,delivery_fee,payment_method,sales_channel,order_status,delivery_status,delivery_days,customer_rating,return_flag
3283,CUST03284,ORD003284,PRD0018,2348011168316,Customer 3284,Male,26-35,Abuja,North Central,Business,...,0.10,27000.0,1500,Cash on Delivery,NaN,Completed,Delivered,12.0,2.0,NaN
4085,CUST04086,ORD004086,PRD0003,2348025998446,Customer 4086,F,36-45,Kaduna,North West,Regular,...,0.15,318750.0,0,Card,Store,Returned,delivered,2.0,1.0,NaN
3229,CUST03230,ORD003230,PRD0010,2348016439473,Customer 3230,Female,46-60,Kaduna,North West,Regular,...,0.10,67500.0,1000,CARD,Store,Cancelled,Delayed,9.0,5.0,Yes
3440,CUST03441,ORD003441,PRD0023,2348066626859,Customer 3441,Female,36-45,Ibadan,South West,Premium,...,0.05,47500.0,2500,Card,NaN,cancelled,Delivered,9.0,3.0,No
2328,CUST02329,ORD002329,PRD0026,2348014728932,Customer 2329,Male,26-35,Port Harcourt,South South,premium,...,0.10,45000.0,0,bank transfer,website,Completed,delivered,9.0,4.0,Yes

In [43]:
urbannest_df.shape

(5000, 25)

In [44]:
urbannest_df.columns

Index(['customer_id', 'order_id', 'product_id', 'phone_number',
       'customer_name', 'gender', 'age_group', 'city', 'region',
       'customer_segment', 'order_date', 'product_category', 'product_name',
       'quantity', 'unit_price', 'discount_rate', 'order_revenue',
       'delivery_fee', 'payment_method', 'sales_channel', 'order_status',
       'delivery_status', 'delivery_days', 'customer_rating', 'return_flag'],
      dtype='str')

In [45]:
urbannest_df_copy = urbannest_df.copy()

In [46]:
# Trim whitespace in text columns.
text_cols = urbannest_df_copy.select_dtypes(include="str").columns
urbannest_df_copy[text_cols] = urbannest_df_copy[text_cols].apply(
    lambda column: column.str.strip()
)

In [47]:
# Standardize known gender values; treat "Unknown" as missing.
gender = urbannest_df_copy["gender"].str.casefold()
urbannest_df_copy["gender"] = gender.map({
    "m": "Male",
    "male": "Male",
    "f": "Female",
    "female": "Female",
    "unknown": pd.NA,
})

In [48]:
# Normalize city spelling and capitalization.
city = urbannest_df_copy["city"].str.casefold()
urbannest_df_copy["city"] = (
    city.replace({"portharcourt": "port harcourt"}).str.title()
)

In [49]:
urbannest_df_copy.head()

,customer_id,order_id,product_id,phone_number,customer_name,gender,age_group,city,region,customer_segment,...,discount_rate,order_revenue,delivery_fee,payment_method,sales_channel,order_status,delivery_status,delivery_days,customer_rating,return_flag
0,CUST00001,ORD000001,PRD0017,2348082692761,Customer 1,NaN,60+,Abuja,North Central,Occasional,...,0.20,40000.0,2500,Bank Transfer,Mobile App,cancelled,delivered,2.0,4.0,NO
1,CUST00002,ORD000002,PRD0004,2348059532120,Customer 2,Male,46-60,Kaduna,North West,NaN,...,0.05,76000.0,1000,Card,Instagram,Completed,Delayed,14.0,5.0,No
2,CUST00003,ORD000003,PRD0002,2348056395726,Customer 3,Female,60+,Kaduna,North West,Regular,...,0.00,375000.0,0,Card,Mobile App,NaN,delivered,1.0,NaN,Yes
3,CUST00004,ORD000004,PRD0020,2348080821128,Customer 4,Female,46-60,Port Harcourt,South South,Regular,...,0.00,375000.0,1000,Cash on Delivery,Store,Returned,Delayed,5.0,4.0,No
4,CUST00005,ORD000005,PRD0021,2348036427770,Customer 5,Male,60+,Port Harcourt,South South,Premium,...,0.20,14000.0,2500,Wallet,Store,Completed,delivered,10.0,3.0,No

In [50]:
# Standardize inconsistent category values.
status = urbannest_df_copy["order_status"].str.casefold()
urbannest_df_copy["order_status"] = (
    status.replace({"cancelled": "Cancelled"}).str.title()
)

payment = urbannest_df_copy["payment_method"].str.casefold()
urbannest_df_copy["payment_method"] = (
    payment.replace({"CARD": "Card"}).str.title()
)

sales = urbannest_df_copy["sales_channel"].str.casefold()
urbannest_df_copy["sales_channel"] = (
    sales.replace({"mobile app": "Mobile App"}).str.title()
)

status = urbannest_df_copy["delivery_status"].str.casefold()
urbannest_df_copy["delivery_status"] = (
    status.replace({"delivered": "Delivered"}).str.title()
)

flag = urbannest_df_copy["return_flag"].str.casefold()
urbannest_df_copy["return_flag"] = (
    flag.replace({"NO": "No", "YES": "Yes"}).str.title()
)

In [64]:
# Add subtotal column for analysis.
urbannest_df_copy["subtotal"] = urbannest_df_copy["quantity"] * urbannest_df_copy["unit_price"]

In [52]:
#
urbannest_df_copy.insert(
    urbannest_df_copy.columns.get_loc("unit_price") + 1,
    "subtotal",
    urbannest_df_copy.pop("subtotal")
)

In [53]:
# Display prices with thousands separators without changing the original numeric column.
urbannest_df_copy.assign(
    unit_price=lambda df: df["unit_price"].map("{:,.0f}".format),
    order_revenue=lambda df: df["order_revenue"].map("{:,.0f}".format),
    delivery_fee=lambda df: df["delivery_fee"].map("{:,.0f}".format),
    subtotal=lambda df: df["subtotal"].map("{:,.0f}".format)
)

,customer_id,order_id,product_id,phone_number,customer_name,gender,age_group,city,region,customer_segment,...,discount_rate,order_revenue,delivery_fee,payment_method,sales_channel,order_status,delivery_status,delivery_days,customer_rating,return_flag
0,CUST00001,ORD000001,PRD0017,2348082692761,Customer 1,NaN,60+,Abuja,North Central,Occasional,...,0.20,"40,000","2,500",Bank Transfer,Mobile App,Cancelled,Delivered,2.0,4.0,No
1,CUST00002,ORD000002,PRD0004,2348059532120,Customer 2,Male,46-60,Kaduna,North West,NaN,...,0.05,"76,000","1,000",Card,Instagram,Completed,Delayed,14.0,5.0,No
2,CUST00003,ORD000003,PRD0002,2348056395726,Customer 3,Female,60+,Kaduna,North West,Regular,...,0.00,"375,000",0,Card,Mobile App,NaN,Delivered,1.0,NaN,Yes
3,CUST00004,ORD000004,PRD0020,2348080821128,Customer 4,Female,46-60,Port Harcourt,South South,Regular,...,0.00,"375,000","1,000",Cash On Delivery,Store,Returned,Delayed,5.0,4.0,No
4,CUST00005,ORD000005,PRD0021,2348036427770,Customer 5,Male,60+,Port Harcourt,South South,Premium,...,0.20,"14,000","2,500",Wallet,Store,Completed,Delivered,10.0,3.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,CUST04996,ORD004996,PRD0008,2348082415426,Customer 4996,NaN,NaN,Kano,North West,premium,...,0.05,"570,000","2,500",Bank Transfer,Instagram,Completed,Delivered,NaN,4.0,No
4996,CUST04997,ORD004997,PRD0030,2348094150958,Customer 4997,Male,60+,Kaduna,North West,Regular,...,0.05,"42,750",0,Bank Transfer,Marketplace,Returned,In Transit,NaN,4.0,No
4997,CUST04998,ORD004998,PRD0002,2348052007276,Customer 4998,NaN,36-45,Abuja,North Central,premium,...,0.15,"17,000","3,500",Ussd,Mobile App,Completed,In Transit,4.0,4.0,Yes
4998,CUST04999,ORD004999,PRD0021,2348078351557,Customer 4999,Male,18-25,Benin City,South South,premium,...,0.10,"216,000","1,000",Cash On Delivery,Website,Completed,Delivered,13.0,4.0,Yes
4999,CUST05000,ORD005000,PRD0010,2348075328308,Customer 5000,NaN,36-45,Ibadan,South West,Regular,...,0.05,"35,625","3,500",Bank Transfer,Store,Completed,In Transit,11.0,4.0,No

In [54]:
# Convert data type of date column to datetime.
urbannest_df_copy["order_date"] = pd.to_datetime(
    urbannest_df_copy["order_date"], errors="coerce"
)

In [66]:
# Add order_month column for analysis, and use month names.
urbannest_df_copy["order_month"] = urbannest_df_copy["order_date"].dt.month_name()

In [65]:
# Add order_year columns for analysis.
urbannest_df_copy["order_year"] = urbannest_df_copy["order_date"].dt.year

In [67]:

# Rearrange columns to place order_month and order_year after order_date.
columns = [
    column
    for column in urbannest_df_copy.columns
    if column not in ("order_month", "order_year")
]
date_index = columns.index("order_date")
columns[date_index + 1 : date_index + 1] = ["order_month", "order_year"]
urbannest_df_copy = urbannest_df_copy[columns]

In [68]:
# Convert data types for date and phone number columns.
urbannest_df_copy["phone_number"] = urbannest_df_copy["phone_number"].astype("string")

In [69]:
# Mask phone numbers to show only the first three and last two digits, replacing the middle digits with asterisks.
urbannest_df_copy["phone_number"] = urbannest_df_copy["phone_number"].str.replace(r"^(\d{3})\d+(\d{2})$", lambda m: m.group(1) + "*" * (len(m.group(0)) - 5) + m.group(2), regex=True)

In [70]:
urbannest_df_copy.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 28 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       5000 non-null   str
 1   order_id          5000 non-null   str
 2   product_id        5000 non-null   str
 3   phone_number      5000 non-null   string
 4   customer_name     5000 non-null   str
 5   gender            4020 non-null   str
 6   age_group         4137 non-null   str
 7   city              5000 non-null   str
 8   region            5000 non-null   str
 9   customer_segment  4615 non-null   str
 10  order_date        5000 non-null   datetime64[us]
 11  order_month       5000 non-null   str
 12  order_year        5000 non-null   int32
 13  product_category  5000 non-null   str
 14  product_name      5000 non-null   str
 15  quantity          5000 non-null   int64
 16  unit_price        5000 non-null   int64
 17  subtotal          5000 non-null   int64
 18  discount_rate     5000 non-null   float64
 19  order_revenue     5000 non-null   float64
 20  delivery_fee      5000 non-null   int64
 21  payment_method    4585 non-null   str
 22  sales_channel     4589 non-null   str
 23  order_status      4295 non-null   str
 24  delivery_status   4206 non-null   str
 25  delivery_days     4582 non-null   float64
 26  customer_rating   4495 non-null   float64
 27  return_flag       4015 non-null   str
dtypes: datetime64[us](1), float64(4), int32(1), int64(4), str(17), string(1)
memory usage: 1.0 MB

In [61]:
# Review remaining missing values rather than dropping many rows.
print(urbannest_df_copy.isna().sum().sort_values(ascending=False).head(10))

return_flag         985
gender              980
age_group           863
delivery_status     794
order_status        705
customer_rating     505
delivery_days       418
payment_method      415
sales_channel       411
customer_segment    385
dtype: int64

In [71]:
urbannest_df_copy.head(5)

,customer_id,order_id,product_id,phone_number,customer_name,gender,age_group,city,region,customer_segment,...,discount_rate,order_revenue,delivery_fee,payment_method,sales_channel,order_status,delivery_status,delivery_days,customer_rating,return_flag
0,CUST00001,ORD000001,PRD0017,234********61,Customer 1,NaN,60+,Abuja,North Central,Occasional,...,0.20,40000.0,2500,Bank Transfer,Mobile App,Cancelled,Delivered,2.0,4.0,No
1,CUST00002,ORD000002,PRD0004,234********20,Customer 2,Male,46-60,Kaduna,North West,NaN,...,0.05,76000.0,1000,Card,Instagram,Completed,Delayed,14.0,5.0,No
2,CUST00003,ORD000003,PRD0002,234********26,Customer 3,Female,60+,Kaduna,North West,Regular,...,0.00,375000.0,0,Card,Mobile App,NaN,Delivered,1.0,NaN,Yes
3,CUST00004,ORD000004,PRD0020,234********28,Customer 4,Female,46-60,Port Harcourt,South South,Regular,...,0.00,375000.0,1000,Cash On Delivery,Store,Returned,Delayed,5.0,4.0,No
4,CUST00005,ORD000005,PRD0021,234********70,Customer 5,Male,60+,Port Harcourt,South South,Premium,...,0.20,14000.0,2500,Wallet,Store,Completed,Delivered,10.0,3.0,No

In [73]:
db_username = 'postgres'
password = 'password'
host = 'localhost'
port = '5432'
database = 'urbannest_db'

from sqlalchemy import create_engine

engine = create_engine(f'postgresql+psycopg2://{db_username}:{password}@{host}:{port}/{database}')

table_name = 'urbannest_data'

urbannest_df_copy.to_sql(name=table_name, con=engine, if_exists='replace', index=False)

1000